# -*- coding: utf-8 -*-
"""async.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pOZXYro3pXNPeWXYWGaqEN0IlYiecvtR
"""

import time
import asyncio

async def fetch_data(id,delay):
    print("data is fetched... id:",id)
    await asyncio.sleep(delay)
    print("data received...id:",id)
    return {"id":id,"data":"some data"}

async def main():
    print("start")
    tasks=[]

    for id,delay in enumerate([2,1,3],start=1):
        tasks.append(asyncio.create_task(fetch_data(id,delay)))
    
  
    await asyncio.gather(*tasks)

    print("end")

t=time.time()
asyncio.run(main())
print(time.time()-t)