# -*- coding: utf-8 -*-
"""async.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pOZXYro3pXNPeWXYWGaqEN0IlYiecvtR
"""

import time
import asyncio

async def fetch_data(id,delay):
    print("data is fetched... id:",id)
    await asyncio.sleep(delay)
    print("data received...id:",id)
    return {"id":id,"data":"some data"}

async def main():
    print("start")
    results=await asyncio.gather(fetch_data(1,2),fetch_data(2,3),fetch_data(3,1))
  
    for result in results:
        print(result)

    print("end")

t=time.time()
asyncio.run(main())
print(time.time()-t)